   FROM parity/parity:stable
   COPY ./deployment/chain/spec.json:/home/parity/spec.json:ro
   COPY ./deployment/chain/reserved_peers:/home/parity/reserved_peers:ro
   COPY ./deployment/NODE_NAME/password:/home/parity/password:ro
   COPY ./deployment/NODE_NAME/authority.toml:/home/parity/authority.toml:ro
   COPY ./deployment/NODE_NAME/${NETWORK_NAME}:/home/parity/data/keys/${NETWORK_NAME}
   COPY ./deployment/NODE_NAME/key.priv:/home/parity/data/network/key
   COPY ./data/NODE_NAME:/home/parity/data
   WORKDIR "/home/""
   EXPOSE 8080
   EXPOSE 8180
   EXPOSE 8545
   EXPOSE 8546
   EXPOSE 30303 
   CMD ["--chain","/home/parity/spec.json", "--config", "/home/parity/authority.toml", "-d","/home/parity/data"]
  